export const assets = {
  close: require('@/assets/icons/close.svg').default,
  logo: require('@/assets/icons/kresus logo mark - white.svg').default,
  cardAccount: require('@/assets/icons/secure account card.svg').default,
  colorGreenPurple: require('@/assets/icons/colors=green purple, interactive=no.png'),
  closeIcon: require('@/assets/icons/close-icon.svg').default,
  sucess: require('@/assets/icons/success-tick.svg').default,
  swapExplore: require('@/assets/icons/swap-explore.svg').default,
  alignIcon: require('@/assets/icons/alignIcon.svg').default,
  bgColor: require('@/assets/icons/bgColor.svg').default,
  text: require('@/assets/icons/text.svg').default,
  colors: require('@/assets/icons/colors.svg').default,
  swapButton: require('@/assets/icons/swipe button.svg').default,
  kresus: require('@/assets/icons/kresus.com.svg').default,
  anotherMint: require('@/assets/icons/mint another.png'),
  copy: require('@/assets/icons/copy.png'),
  bar: require('@/assets/icons/Bar.svg').default,
  nfts: require('@/assets/icons/nfts.png'),
  camera_blue: require('@/assets/icons/camera-blue.svg').default,
  crop_bg: require('@/assets/icons/crop-bg.svg').default,
  arrow_right: require('@/assets/icons/arrow-right.svg').default,
  back: require('@/assets/icons/back.svg').default,
  closeButton: require('@/assets/icons/close-button.svg').default,
  dollar: require('@/assets/icons/dollar.svg'),
  tick: require('@/assets/icons/tick.svg').default,
  world_app: require('@/assets/icons/world-app.svg').default,
  chevron_right: require('@/assets/icons/chevron-right.svg').default,
};
